alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gds='git diff --staged'
alias gc='git commit'
alias gg='git grep'
alias gl='git log'
alias gp='git push'

alias s='sbt'
alias st='sbt test'
alias sit='sbt it:test'
alias dsbt='SBT_OPTS="$SBT_OPTS  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005" sbt'
